Grabbing training data...
Grabbing testing data...
Training EPOCH 0:
/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:126: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
quantiles_train Quantile loss is: 45.873180891338144
Training EPOCH 1:
quantiles_train Quantile loss is: 39.78621954666941
test set loss is: 13.680168151855469
> /Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py(304)run_cqr()
    303     # --- Calculate the coverage from the un-calibrated predictions
--> 304     uncal_coverage = calculate_coverage(uncal_predictions_t[0][:,0,:,:], uncal_predictions_t[0][:,2,:,:], test_loader)
    305     print('Quantile Regression Coverage without conformal is: {}'.format(uncal_coverage))
*** AttributeError: 'list' object has no attribute 'shape'
3
(32, 3, 31, 49)
(32, 31, 49)
(32, 31, 49)
*** AttributeError: 'DataLoader' object has no attribute 'shape'
<torch.utils.data.dataloader.DataLoader object at 0x1150ae650>
*** NameError: name 'y_data' is not defined
torch.Size([28, 51, 31, 49])
torch.Size([28, 1, 31, 49])
32
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_pipeline.py", line 133, in <module>
    run_cqr(unet, device, aq_train_dataset, aq_test_dataset, save_dir, experiment, 0.1, args.channels,
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py", line 304, in run_cqr
    print('Quantile Regression Coverage without conformal is: {}'.format(uncal_coverage))
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py", line 304, in run_cqr
    print('Quantile Regression Coverage without conformal is: {}'.format(uncal_coverage))
  File "/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.25.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True