Grabbing training data...
Grabbing testing data...
Training EPOCH 0:
/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:126: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
quantiles_train Quantile loss is: 44.65791983353464
Training EPOCH 1:
quantiles_train Quantile loss is: 30.75592121325041
test set loss is: 13.036046028137207
Quantile Regression Coverage without conformal is: 0.7158742988708453
Predicting on calibration set...
test set loss is: 13.128059387207031
Calculating qyhat for calibration...
Calibrating Test set predictions...
> /Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py(337)run_cqr()
    336     ipdb.set_trace()
--> 337     cal_coverage = calculate_coverage(cal_lower_preds_t[0][:,0,:,:], cal_upper_preds_t[0][:,2,:,:], test_loader)
    338     print('Conformalized Quantile Regression Coverage is: {}'.format(cal_coverage))
(32, 3, 31, 49)
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_pipeline.py", line 133, in <module>
    run_cqr(unet, device, aq_train_dataset, aq_test_dataset, save_dir, experiment, 0.1, args.channels,
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py", line 337, in run_cqr
    cal_coverage = calculate_coverage(cal_lower_preds_t[0][:,0,:,:], cal_upper_preds_t[0][:,2,:,:], test_loader)
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py", line 337, in run_cqr
    cal_coverage = calculate_coverage(cal_lower_preds_t[0][:,0,:,:], cal_upper_preds_t[0][:,2,:,:], test_loader)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.25.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True